# Generated by Django 4.0.5 on 2023-02-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaic', '0004_submission_promo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleresult',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_results', to='formulaic.field'),
        ),
    ]
