# Generated by Django 4.0.5 on 2024-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('formulaic', '0005_alter_form_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='display_name',
            field=models.TextField(),
        ),
    ]
