version: '3'

services:
    db:
        image: postgres:12.4
        volumes:
            - ./../postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
    web:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure:1
        command: >
            sh -c "
                python manage.py makemigrations formulaic &&
                python manage.py makemigrations example_project &&
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
            "
            # 
            # python manage.py migrate

